import { buildAnalysisPdf } from "@/services/pdf";
import { emitRealtimeEvent } from "@/lib/socket";
import { prisma } from "@/lib/prisma";
import { uploadBufferToR2 } from "@/lib/r2";
import { AiAnalysisResponse } from "@/types";

export async function createHealthAnalysis(vehicleId: string, aiResult: AiAnalysisResponse) {
  const vehicle = await prisma.vehicle.findUnique({
    where: { id: vehicleId },
    include: { images: true },
  });

  if (!vehicle) {
    throw new Error("Vehicle record not found.");
  }

  let summary = aiResult.summary?.trim() || "";
  
  if (!summary) {
    if (aiResult.issues.length === 0) {
      summary = "No major issues detected";
    } else {
      summary = `Detected ${aiResult.issues.length} issue${aiResult.issues.length !== 1 ? "s" : ""}.`;
    }
  }

  const analysis = await prisma.healthAnalysis.create({
    data: {
      vehicleId,
      conditionScore: aiResult.conditionScore,
      riskLevel: aiResult.riskLevel,
      analysisStatus: "Processing",
      summary: summary || "No major issues detected",
    },
  });

  let visibleCount = 0;
  for (const issue of aiResult.issues) {
    const hidden = issue.hidden ?? visibleCount >= 10;
    const detection = await prisma.aiDetection.create({
      data: {
        vehicleId,
        title: issue.title,
        severity: issue.severity,
        confidence: issue.confidence,
        repairEstimate: issue.repairEstimate,
        riskLevel: issue.riskLevel,
        hidden,
      },
    });

    emitRealtimeEvent("ai_issue_detected", {
      analysisId: analysis.id,
      detection: {
        id: detection.id,
        title: detection.title,
        severity: detection.severity,
        confidence: detection.confidence,
        repairEstimate: detection.repairEstimate,
        riskLevel: detection.riskLevel,
      },
    });

    visibleCount += 1;
  }

  emitRealtimeEvent("condition_score_updated", {
    analysisId: analysis.id,
    conditionScore: aiResult.conditionScore,
  });

  await prisma.vehicle.update({
    where: { id: vehicleId },
    data: { analysisStatus: "Processing" },
  });

  return analysis;
}

export async function generateFullAnalysisPdf(analysisId: string) {
  const analysis = await prisma.healthAnalysis.findUnique({
    where: { id: analysisId },
    include: {
      vehicle: {
        include: { images: true, detections: true },
      },
    },
  });

  if (!analysis) {
    throw new Error("Analysis not found.");
  }

  const imageUrls = (analysis.vehicle.images as any[]).map((image) => image.imageUrl);
  const detections = (analysis.vehicle.detections as any[]).map((issue) => ({
    title: issue.title,
    severity: issue.severity,
    confidence: issue.confidence,
    repairEstimate: issue.repairEstimate,
    riskLevel: issue.riskLevel,
    hidden: issue.hidden,
  }));

  const pdfBuffer = await buildAnalysisPdf(
    {
      id: analysis.id,
      conditionScore: analysis.conditionScore,
      riskLevel: analysis.riskLevel,
      analysisStatus: analysis.analysisStatus,
      createdAt: analysis.createdAt,
    },
    analysis.vehicle.vehicleName,
    imageUrls,
    detections,
    `This is a premium inspection summary generated by Car Bronze for ${analysis.vehicle.vehicleName}.`,
  );

  const pdfKey = `pdfs/${analysis.id}.pdf`;
  const pdfUrl = await uploadBufferToR2(pdfKey, pdfBuffer, "application/pdf");

  await prisma.healthAnalysis.update({
    where: { id: analysisId },
    data: {
      analysisPdfUrl: pdfUrl,
      analysisStatus: "Delivered",
    },
  });

  emitRealtimeEvent("analysis_ready", {
    analysisId,
    pdfUrl,
  });

  return pdfUrl;
}
